config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  root "lists#index"

  resources :lists do
    resources :tasks
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, presence: true

  normalizes :name, with: -> { _1.strip }

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :name, presence: true

  normalizes :name, with: -> { _1.strip }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to action: 'show', id: @list.id
    else
      render action: 'new'
    end
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def new
    @task = Task.new
  end

  def create
    @task = @list.tasks.build(task_params)
    if @task.save
        redirect_to @list, notice: 'Task was successfully created.'
    else
        render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_task
    @task = @list.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/_lists_link.html.erb
<%= link_to "Back to lists", lists_path, class: "hover:underline" %>

app/views/lists/index.html.erb
<div>
  <h1 class="page-title">Todo lists</h1>

  <ul class="p-1 my-2">
  <% @lists.each do |list| %>
    <li class="p-1 m-1 text-black bg-gray-300 hover:bg-orange-300 hover:underline rounded"><%= link_to list.name, list %></li>
  <% end %>
  </ul>

  <%= link_to "New list", new_list_path, class: "btn-primary" %>
</div>

app/views/lists/new.html.erb
<div>
    <h1 class="font-bold text-4xl">Create new list</h1>

    <%= form_with model: @list do |form| %>
        <%= form.text_field :name %>
        <%= form.submit "Create list", class: "btn-primary" %>
    <% end %>

    <%= render 'lists_link' %>
</div>

app/views/lists/show.html.erb
<div>
    <h1 class="page-title"><%= @list.name %></h1>

    <ul class="p-1 my-2">
    <% @list.tasks.each do |task| %>
        <li><%= task.name %></li>
    <% end %>
    </ul>

    <%= link_to "New task", new_list_task_path(@list), class: "btn-primary" %>

    <%= render 'lists_link' %>
</div>

app/views/tasks/new.html.erb
<div>
    <h1 class="font-bold text-4xl">Create new Task in: <%= @list.name %></h1>

    <%= form_with(model: [@list, @task]) do |form| %>
        <%= form.label :name %>
        <%= form.text_field :name %>
        <%= form.label :description %>
        <%= form.text_field :description %>
        <%= form.submit "Create Task", class: "btn-primary" %>
    <% end %>

    <%= link_to "Back to list tasks", @list %>

</div>